
---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install git
    yum: name=git state=present
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started