
---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install git
    yum: name=git state=present
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Dowload PHP source code base repo
    git:
      repo: 'https://github.com/sagar-unix/projCert.git'
      dest: /home/ec2-user/jenkins/workspace/devops